### ISSUE TITLE
General question about the code

### ISSUE THREAD

**Issue by lidora-everc** [XMCyber/unique-cidr-manager#13]
what exactly the case if is not overlaping how is reasonable that is equal?
https://github.com/XMCyber/unique-cidr-manager/blob/7f425f26433261183ff5c473fddaf67164b82227/server/cidr.py#L65-L68

**Comment by XMCyber** [comment]
The python package called ipaddress, the function of overlapping is missing on use case - when network are identical. The logic would say that identical is kind of overlapping (full overlapping) but in realty the function will return false on such unique case. For that there is second if statement which asking if the chosen network is identical to pre-occupied
